# ============================================================================
# WARNING: AUTO-GENERATED FILE - DO NOT MODIFY MANUALLY!
# ============================================================================
# This file is automatically generated by client_tools/client_generator.py
# Any manual changes will be overwritten when the generator runs again.
#
# To update this file:
#   1. Modify the source files in src/twinkle/
#   2. Run: python client_tools/client_generator.py
# ============================================================================
from typing import Any, Dict, List, Optional, Union
from twinkle_client.http import http_post
from twinkle.sampler.base import Sampler
from twinkle_client.types.sampler import AddAdapterResponse, SampleResponseModel, SetTemplateResponse
from peft import PeftConfig
from twinkle.data_format import Trajectory, InputFeature


class vLLMSampler(Sampler):
    """Client wrapper for Sampler that calls server HTTP endpoints.

    This client manages sampling operations and adapter synchronization with the sampler server.
    The server-side session (managed by TwinkleClient) keeps the sampler alive.
    """

    def __init__(self, model_id: str, **kwargs):
        """Create the sampler instance on server."""
        from twinkle_client.http import get_base_url
        self.server_url = get_base_url()

        self.adapter_name = None
        if '://' in model_id:
            model_id = model_id.split('://')[1]
        self.server_url = f'{self.server_url}/sampler/{model_id}/twinkle'
        response = http_post(
            url=f'{self.server_url}/create',
            json_data=kwargs
        )
        response.raise_for_status()

    def add_adapter_to_sampler(self, adapter_name: str, config: PeftConfig, **kwargs) -> AddAdapterResponse:
        """Add a new adapter to the sampler."""
        if isinstance(config, PeftConfig):
            config = config.__dict__
        response = http_post(
            url=f'{self.server_url}/add_adapter_to_sampler',
            json_data={'adapter_name': adapter_name, 'config': config, **kwargs}
        )
        response.raise_for_status()
        self.adapter_name = adapter_name
        return AddAdapterResponse(**response.json())

    def sample(
        self,
        inputs: Union[List[Trajectory], List[InputFeature]],
        sampling_params: Optional[Dict[str, Any]] = None,
        adapter_name: str = '',
        adapter_uri: Optional[str] = None,
        num_samples: int = 1,
    ) -> List[SampleResponseModel]:
        """Sample from the model.

        Args:
            inputs: List of Trajectory or InputFeature to sample from.
            sampling_params: Sampling parameters dict.
            adapter_name: Adapter name for LoRA inference.
            adapter_uri: Adapter URI (twinkle:// path or local path) for LoRA inference.
            num_samples: Number of completions to generate per prompt.

        Returns:
            A list of sampleResponseModel with 'sequences' list, each containing tokens, logprobs, stop_reason.
        """
        json_data = {
            'inputs': inputs,
            'sampling_params': sampling_params,
            'adapter_name': adapter_name,
            'num_samples': num_samples,
        }
        if adapter_uri is not None:
            json_data['adapter_uri'] = adapter_uri

        response = http_post(
            url=f'{self.server_url}/sample',
            json_data=json_data
        )
        response.raise_for_status()
        return [SampleResponseModel(**r) for r in response.json()['samples']]

    def set_template(self, template_cls: str, adapter_name: str = '', **kwargs) -> SetTemplateResponse:
        """Set the template for encoding trajectories."""
        response = http_post(
            url=f'{self.server_url}/set_template',
            json_data={'template_cls': template_cls, 'adapter_name': adapter_name, **kwargs}
        )
        response.raise_for_status()
        return SetTemplateResponse(**response.json())

    def apply_patch(self, patch_cls: str, **kwargs) -> None:
        """Apply a patch to the model."""
        response = http_post(
            url=f'{self.server_url}/apply_patch',
            json_data={'patch_cls': patch_cls, 'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()
