# ============================================================================
# WARNING: AUTO-GENERATED FILE - DO NOT MODIFY MANUALLY!
# ============================================================================
# This file is automatically generated by client_tools/client_generator.py
# Any manual changes will be overwritten when the generator runs again.
#
# To update this file:
#   1. Modify the source files in src/twinkle/
#   2. Run: python client_tools/client_generator.py
# ============================================================================
from typing import Any, Dict, Optional
import time
from twinkle_client.http import http_get, http_post
from twinkle_client.types.model import (
    CalculateLossResponse,
    CalculateMetricResponse,
    ClipGradNormResponse,
    ForwardBackwardResponse,
    ForwardResponse,
    GetStateDictResponse,
    GetTrainConfigsResponse,
    SaveResponse,
    TrainingProgressResponse,
)


class MultiLoraTransformersModel:
    """Client wrapper for TwinkleModel that calls server HTTP endpoints.

    This client manages adapters and sends training/inference requests to the model server.
    The server-side session (managed by TwinkleClient) keeps the model alive.
    """

    def __init__(self, model_id: str, **kwargs):
        """Initialize model client."""
        from twinkle_client.http import get_base_url
        self.server_url = get_base_url()

        self.model_id = model_id
        if '://' in model_id:
            model_id = model_id.split('://')[1]
        self.server_url = f'{self.server_url}/model/{model_id}/twinkle'
        self.adapter_name = None
        response = http_post(
            url=f'{self.server_url}/create',
        )
        response.raise_for_status()

    def add_adapter_to_model(self, adapter_name: str, config: Dict[str, Any], **kwargs) -> None:
        """Add a new adapter to the model."""
        response = http_post(
            url=f'{self.server_url}/add_adapter_to_model',
            json_data={'adapter_name': adapter_name, 'config': config, **kwargs}
        )
        response.raise_for_status()
        self.adapter_name = adapter_name

    def forward(self, inputs: Any, **kwargs) -> ForwardResponse:
        """Execute forward pass on the model."""
        response = http_post(
            url=f'{self.server_url}/forward',
            json_data={'inputs': inputs, 'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()
        return ForwardResponse(**response.json())

    def forward_only(self, inputs: Any, **kwargs) -> ForwardResponse:
        """Execute forward pass without gradient computation."""
        response = http_post(
            url=f'{self.server_url}/forward_only',
            json_data={'inputs': inputs, 'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()
        return ForwardResponse(**response.json())

    def calculate_loss(self, **kwargs) -> CalculateLossResponse:
        """Calculate loss from model outputs."""
        response = http_post(
            url=f'{self.server_url}/calculate_loss',
            json_data={'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()
        return CalculateLossResponse(**response.json())

    def get_train_configs(self, **kwargs) -> GetTrainConfigsResponse:
        """Get training configs."""
        response = http_post(
            url=f'{self.server_url}/get_train_configs',
            json_data={'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()
        return GetTrainConfigsResponse(**response.json())

    def backward(self, **kwargs) -> None:
        """Execute backward pass."""
        response = http_post(
            url=f'{self.server_url}/backward',
            json_data={'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()

    def forward_backward(self, inputs: Any, **kwargs) -> ForwardBackwardResponse:
        """Execute combined forward and backward pass."""
        response = http_post(
            url=f'{self.server_url}/forward_backward',
            json_data={'inputs': inputs, 'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()
        return ForwardBackwardResponse(**response.json())

    def step(self, **kwargs) -> None:
        """Execute optimizer step."""
        response = http_post(
            url=f'{self.server_url}/step',
            json_data={'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()

    def zero_grad(self, **kwargs) -> None:
        """Zero out gradients."""
        response = http_post(
            url=f'{self.server_url}/zero_grad',
            json_data={'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()

    def lr_step(self, **kwargs) -> None:
        """Execute learning rate scheduler step."""
        response = http_post(
            url=f'{self.server_url}/lr_step',
            json_data={'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()

    def clip_grad_norm(self, max_grad_norm: float = 1.0, norm_type: int = 2, **kwargs) -> ClipGradNormResponse:
        """Clip gradient norm."""
        response = http_post(
            url=f'{self.server_url}/clip_grad_norm',
            json_data={'max_grad_norm': max_grad_norm, 'norm_type': norm_type, 'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()
        return ClipGradNormResponse(**response.json())

    def clip_grad_and_step(self, max_grad_norm: float = 1.0, norm_type: int = 2, **kwargs) -> None:
        """Clip gradient norm and execute optimizer step in one call."""
        response = http_post(
            url=f'{self.server_url}/clip_grad_and_step',
            json_data={'max_grad_norm': max_grad_norm, 'norm_type': norm_type, 'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()

    def set_loss(self, loss_cls: str, **kwargs) -> None:
        """Set the loss function."""
        response = http_post(
            url=f'{self.server_url}/set_loss',
            json_data={'loss_cls': loss_cls, 'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()

    def set_optimizer(self, optimizer_cls: str, **kwargs) -> None:
        """Set the optimizer."""
        response = http_post(
            url=f'{self.server_url}/set_optimizer',
            json_data={'optimizer_cls': optimizer_cls, 'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()

    def set_lr_scheduler(self, scheduler_cls: str, **kwargs) -> None:
        """Set the learning rate scheduler."""
        response = http_post(
            url=f'{self.server_url}/set_lr_scheduler',
            json_data={'scheduler_cls': scheduler_cls, 'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()

    def save(self, name: str, **kwargs) -> SaveResponse:
        """Save model checkpoint."""
        response = http_post(
            url=f'{self.server_url}/save',
            json_data={'name': name, 'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()
        return SaveResponse(**response.json())

    def load(self, name: str, **kwargs) -> None:
        """Load model checkpoint."""
        response = http_post(
            url=f'{self.server_url}/load',
            json_data={'name': name, 'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()

    def resume_from_checkpoint(self, name: str, *, resume_only_model: bool = False, **kwargs) -> Dict[str, Any]:
        response = http_post(
            url=f'{self.server_url}/resume_from_checkpoint',
            json_data={'name': name, 'adapter_name': self.adapter_name,
                       'resume_only_model': resume_only_model, **kwargs}
        )
        response.raise_for_status()
        return TrainingProgressResponse(**response.json()).result

    def apply_patch(self, patch_cls: str, **kwargs) -> None:
        """Apply a patch to the model."""
        response = http_post(
            url=f'{self.server_url}/apply_patch',
            json_data={'patch_cls': patch_cls, 'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()

    def add_metric(self, metric_cls: str, is_training: Optional[bool] = None, **kwargs) -> None:
        """Add a metric to the model."""
        response = http_post(
            url=f'{self.server_url}/add_metric',
            json_data={'metric_cls': metric_cls, 'is_training': is_training, 'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()

    def set_template(self, template_cls: str, **kwargs) -> None:
        """Set the template for data processing."""
        response = http_post(
            url=f'{self.server_url}/set_template',
            json_data={'template_cls': template_cls, 'adapter_name': self.adapter_name, 'model_id': self.model_id, **kwargs}
        )
        response.raise_for_status()

    def set_processor(self, processor_cls: str, **kwargs) -> None:
        """Set the input processor."""
        response = http_post(
            url=f'{self.server_url}/set_processor',
            json_data={'processor_cls': processor_cls, 'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()

    def calculate_metric(self, is_training: bool = True, **kwargs) -> CalculateMetricResponse:
        """Calculate metrics from model outputs."""
        response = http_post(
            url=f'{self.server_url}/calculate_metric',
            json_data={'is_training': is_training, 'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()
        return CalculateMetricResponse(**response.json())

    def get_state_dict(self, **kwargs) -> GetStateDictResponse:
        """Get model state dictionary."""
        response = http_post(
            url=f'{self.server_url}/get_state_dict',
            json_data={'adapter_name': self.adapter_name, **kwargs}
        )
        response.raise_for_status()
        return GetStateDictResponse(**response.json())

    def upload_to_hub(
        self,
        checkpoint_dir: str,
        hub_model_id: str,
        hub_token: Optional[str] = None,
        async_upload: bool = True,
        poll_interval: float = 5.0,
    ) -> None:
        """Upload model checkpoint to hub.

        Submits the upload task to the server and polls for completion.
        Blocks until the upload finishes or raises on failure.

        Args:
            checkpoint_dir: The directory path of the checkpoint to upload.
            hub_model_id: The hub model id.
            hub_token: The hub token (optional).
            async_upload: Deprecated, has no effect. The server always runs the
                upload in the background and the client polls for completion.
            poll_interval: Seconds between status poll requests (default: 5).
        """
        response = http_post(
            url=f'{self.server_url}/upload_to_hub',
            json_data={
                'checkpoint_dir': checkpoint_dir,
                'hub_model_id': hub_model_id,
                'hub_token': hub_token,
            }
        )
        response.raise_for_status()
        request_id = response.json().get('request_id')
        if not request_id:
            return

        print(f'[upload_to_hub] Upload started (task {request_id}), waiting for completion...')
        while True:
            status_resp = http_get(url=f'{self.server_url}/upload_status/{request_id}')
            status_resp.raise_for_status()
            data = status_resp.json()
            status = data.get('status', 'unknown')
            if status == 'completed':
                print(f'[upload_to_hub] Upload completed successfully.')
                return
            elif status == 'failed':
                error = data.get('error', 'Unknown error')
                raise RuntimeError(f'[upload_to_hub] Upload failed: {error}')
            else:
                print(f'[upload_to_hub] Status: {status}...')
                time.sleep(poll_interval)
